<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Vn bn ngun_QFw9Te_1</name>
   <tag></tag>
   <elementGuidId>110deb50-4302-43d2-814e-d1ca7a1667c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='yDmH0d']/c-wiz/div/div[2]/c-wiz/div[2]/c-wiz/div/div[2]/div[3]/c-wiz/span/span/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.QFw9Te</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d7f680eb-2d79-4acc-b776-02cf82b67725</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>QFw9Te</value>
      <webElementGuid>e97d3104-cd57-4a4f-b90a-c57b48bbe329</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jsaction</name>
      <type>Main</type>
      <value>rcuQ6b:pdOLIe,rysOMe;agoMJf:EWnfbd;qmOkV:ZTCSKe,ypQoS,peH7Nc;VjXcvc:lVRyvf,kQslJf;CpMfbe:g81FKd,kCq1A,NkJOu,pkQzee,pc2EQb,mByJ6b,MLW7ce,gx3W4c,Kn2pB,JcS7v;Qhw78b:oDNoof;s2yng:CLZnDb,TXpe8b;lJyiZb:qaDTSe,HOic6b,ZTCSKe;ssxfTe:qH83Jb;RDfcSe:aIx5xb;zzJfGb:lI0Nd;A5dP1b:H3p8Qb,ZTCSKe;SuwQzc:VROTkf;</value>
      <webElementGuid>52a6d99a-a343-45f5-a482-33cd40fa9f60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jscontroller</name>
      <type>Main</type>
      <value>mmcjze</value>
      <webElementGuid>5a3eedfa-c1d2-4cfe-9765-a6ddc6470fdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jsmodel</name>
      <type>Main</type>
      <value>s2VbJb MDB2J glibvb</value>
      <webElementGuid>a1410df6-4da8-40b6-a018-91a5c5025dd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jsname</name>
      <type>Main</type>
      <value>T118cc</value>
      <webElementGuid>944bb79b-1954-489a-846d-7c5a266799cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;yDmH0d&quot;)/c-wiz[@class=&quot;zQTmif SSPGKf RvYhPd BIdYQ aL9XFd&quot;]/div[@class=&quot;T4LgNb&quot;]/div[@class=&quot;WFnNle&quot;]/c-wiz[@class=&quot;MOkH4e BSw7K iYelWb yF6Zo&quot;]/div[@class=&quot;OlSOob&quot;]/c-wiz[@class=&quot;QsA0jb&quot;]/div[@class=&quot;ccvoYb EjH7wc&quot;]/div[@class=&quot;AxqVh&quot;]/div[@class=&quot;OPPzxe&quot;]/c-wiz[@class=&quot;rm1UF UnxENd&quot;]/span[1]/span[1]/div[@class=&quot;QFw9Te&quot;]</value>
      <webElementGuid>02e80db4-daab-4870-a702-fb158c02947d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='yDmH0d']/c-wiz/div/div[2]/c-wiz/div[2]/c-wiz/div/div[2]/div[3]/c-wiz/span/span/div</value>
      <webElementGuid>3b90ca4c-b6fc-4517-9c97-4ee5f97bc34d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Văn bản nguồn'])[1]/following::div[1]</value>
      <webElementGuid>3bab3237-c232-487e-959b-70e1c7fec6e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Có thể chứa ngôn ngữ nhạy cảm và có tranh chấp'])[1]/following::div[9]</value>
      <webElementGuid>d510dafb-f78e-42d3-af20-74a4f0ac011d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Xóa văn bản nguồn'])[1]/preceding::div[12]</value>
      <webElementGuid>a1298b1e-5b48-4f2c-966b-c4bfe4d5b956</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hiện thêm'])[1]/preceding::div[16]</value>
      <webElementGuid>f8344582-7ee5-4033-afb2-319cd6ee82d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div</value>
      <webElementGuid>e28a1fe6-c663-4d37-a6db-fed442b40f71</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
