<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Vn bn ngun_QFw9Te</name>
   <tag></tag>
   <elementGuidId>53fea719-103e-4327-8a9b-d16de261d2b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='yDmH0d']/c-wiz/div/div[2]/c-wiz/div[2]/c-wiz/div/div[2]/div[3]/c-wiz/span/span/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.QFw9Te</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0190fed3-5e8b-4b8c-868c-b29d9e0064a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>QFw9Te</value>
      <webElementGuid>898933c0-a312-4076-9ff3-57ce1e356b1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jsaction</name>
      <type>Main</type>
      <value>rcuQ6b:pdOLIe,rysOMe;agoMJf:EWnfbd;qmOkV:ZTCSKe,ypQoS,peH7Nc;VjXcvc:lVRyvf,kQslJf;CpMfbe:g81FKd,kCq1A,NkJOu,pkQzee,pc2EQb,mByJ6b,MLW7ce,gx3W4c,Kn2pB,JcS7v;Qhw78b:oDNoof;s2yng:CLZnDb,TXpe8b;lJyiZb:qaDTSe,HOic6b,ZTCSKe;ssxfTe:qH83Jb;RDfcSe:aIx5xb;zzJfGb:lI0Nd;A5dP1b:H3p8Qb,ZTCSKe;SuwQzc:VROTkf;</value>
      <webElementGuid>1b395839-ee7e-4f11-9bc9-963f86db8fac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jscontroller</name>
      <type>Main</type>
      <value>mmcjze</value>
      <webElementGuid>0253ea98-fc75-4019-acda-a288200e2a92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jsmodel</name>
      <type>Main</type>
      <value>s2VbJb MDB2J glibvb</value>
      <webElementGuid>a5633436-0c5c-416c-8a0a-865e1f8e2feb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jsname</name>
      <type>Main</type>
      <value>T118cc</value>
      <webElementGuid>4c38c75c-a533-401b-be11-5fab59831860</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;yDmH0d&quot;)/c-wiz[@class=&quot;zQTmif SSPGKf RvYhPd BIdYQ aL9XFd&quot;]/div[@class=&quot;T4LgNb&quot;]/div[@class=&quot;WFnNle&quot;]/c-wiz[@class=&quot;MOkH4e BSw7K iYelWb yF6Zo&quot;]/div[@class=&quot;OlSOob&quot;]/c-wiz[@class=&quot;QsA0jb&quot;]/div[@class=&quot;ccvoYb EjH7wc&quot;]/div[@class=&quot;AxqVh&quot;]/div[@class=&quot;OPPzxe&quot;]/c-wiz[@class=&quot;rm1UF UnxENd u3bW4e&quot;]/span[1]/span[1]/div[@class=&quot;QFw9Te&quot;]</value>
      <webElementGuid>b99db883-340a-4a7a-ad98-36d9a7dd21e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='yDmH0d']/c-wiz/div/div[2]/c-wiz/div[2]/c-wiz/div/div[2]/div[3]/c-wiz/span/span/div</value>
      <webElementGuid>370c9c1c-a035-47a2-870a-138a04b5e3a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Văn bản nguồn'])[1]/following::div[1]</value>
      <webElementGuid>a3d32d7f-2288-48fd-8e07-073d062953ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Có thể chứa ngôn ngữ nhạy cảm và có tranh chấp'])[1]/following::div[9]</value>
      <webElementGuid>68918939-3eb7-4389-815e-02e622559056</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Xóa văn bản nguồn'])[1]/preceding::div[12]</value>
      <webElementGuid>f8fee494-3f48-455d-b9c4-8a2454bfc92f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hiện thêm'])[1]/preceding::div[16]</value>
      <webElementGuid>07042ca4-16e6-4f31-8e19-0e5d2b7cd712</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div</value>
      <webElementGuid>5b8b7e78-9121-4ab6-b9ca-89225d1bfbcc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
